baseURL = "https://larrywright.me/"
title = "Larry Wright"
languageCode = "en-us"
paginate = "10" # Number of posts per page
theme = "larrywright.me"
pygmentsCodeFences = true

[Author]
    name = "Larry Wright"

[taxonomies]
  category = "categories"
  topic = "topics"
  tag = "tags"

[params]
    subtitle = "The Journal of a Curious Person" # Subtitle of your site
    defaultDescription = "Words and pictures by Larry Wright. A little bit of everything, mostly nerdy."
    facebook = "larrywright"
    twitter = "larrywright"
    linkedin = "https://www.linkedin.com/in/larrywright/"
    github = "https://github.com/larrywright"
    email = "larrywright@gmail.com"
    home = "Home"
    truncate = true
    avatar = "larry.jpg"
    mainSections = ["post","photo","til"]


[params.widgets]
    search = true 
    recent_articles = true 
    categories = true # Enable "Categories" widget
    tags = true # Enable "Tags" widget
        tags_counter = false # Enable counter for each tag in "Tags" widget (disabled by default)


[[menu.main]]
name = "About"
weight = 1
identifier = "about"
url = "/about/me"

[[menu.main]]
name = "Blog"
weight = 2
identifier = "posts"
url = "/post/"

[[menu.main]]
name = "Photos"
weight = 2
identifier = "photo"
url = "/photo/"

[[menu.main]]
name = "Now"
weight = 4
identifier = "now"
url = "/now/"

[[menu.main]]
name = "TIL"
weight = 5
identifier = "til"
url = "/til/"

[markup.goldmark.renderer] 
    unsafe= true

[deployment]

[[deployment.targets]]
# An arbitrary name for this target.
name = "staging"

# S3; see https://gocloud.dev/howto/blob/#s3
URL = "s3://draft.larrywright.me?region=us-east-1"

# If you are using a CloudFront CDN, deploy will invalidate the cache as needed.
cloudFrontDistributionID = "EX64VQR8QFZIN"


# [[deployment.matchers]] configure behavior for files that match the Pattern.
# See https://golang.org/pkg/regexp/syntax/ for pattern syntax.
# Pattern searching is stopped on first match.

# Samples:

[[deployment.matchers]]
# Cache static assets for 1 year.
pattern = "^.+\\.(js|css|svg|ttf)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(png|jpg)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = false

[[deployment.matchers]]
# Set custom content type for /sitemap.xml
pattern = "^sitemap\\.xml$"
contentType = "application/xml"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(html|xml|json)$"
gzip = true