version: 0.2

environment_variables:
  plaintext:
    AWS_DEFAULT_REGION: "us-east-1"
    HUGO_VERSION: "0.118.2"
    HUGO_SHA256: "9c4c1a0ca76519a00742a9e75076648fe71480b302241fb941129ac647f01581"
    BUCKET_NAME: "larrywright.me"

phases:
  install:
    runtime-versions:
      golang: latest
    commands:
      - curl -Ls https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz -o /tmp/hugo.tar.gz
      - echo "${HUGO_SHA256}  /tmp/hugo.tar.gz" | sha256sum -c -
      - tar xf /tmp/hugo.tar.gz -C /tmp
      - mv /tmp/hugo /usr/bin/hugo
      - rm -rf /tmp/hugo*
    finally:
      - hugo version
  build:
    commands:
      - hugo --gc --minify
  post_build:
    commands:
      - hugo deploy --target=production --maxDeletes -1
