version: 0.2

environment_variables:
  plaintext:
    AWS_DEFAULT_REGION: "us-east-1"
    HUGO_VERSION: "0.117.0"
    HUGO_SHA256: "5d136420680ce3ccd6b1f1824332f8e2c97a802890e7b25d14f7e5f343f724a9"
    BUCKET_NAME: "larrywright.me"

phases:
  install:
    runtime-versions:
      golang: latest
    commands:
      - curl -Ls https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz -o /tmp/hugo.tar.gz
      - echo "${HUGO_SHA256}  /tmp/hugo.tar.gz" | sha256sum -c -
      - tar xf /tmp/hugo.tar.gz -C /tmp
      - mv /tmp/hugo /usr/bin/hugo
      - rm -rf /tmp/hugo*
    finally:
      - hugo version
  build:
    commands:
      - hugo
  post_build:
    commands:
      - cd public && aws s3 sync --acl "public-read" --sse "AES256" --delete . s3://$BUCKET_NAME --exclude .DS_Store
