baseurl = "http://beta.larrywright.me/"
languageCode = "en-us"
title = "larrywright.me"
paginate = 5
DisqusShortname = "thecuriousityproject"
Copyright = "All rights reserved - 2015"
canonifyurls = true

[params]
description = "Curiosity Project"
#cover = "images/DeathtoStock_Simplify8.jpg"
cover = "images/IMG_0824.jpg"
author = "Larry Wright"
authorlocation = "Normal, Illinois"
authorwebsite = "http://larrywright.me"
bio = "Curious person; maker of things. Ruby, Chef, Sinatra, Docker, photography. Currently: Chef Lead for the Accenture Cloud Platform. Opinions are my own."
logo = "images/larry.jpg"
googleAnalyticsUserID = "UA-100582-3"
# Optional RSS-Link, if not provided it defaults to the standard index.xml
RSSLink = "http://feeds.feedburner.com/larrywright"
githubName = "larrywright"
twitterName = "larrywright"
facebookName = "larrywright"
# set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
hideHUGOSupport = true

[[menu.main]]
name = "Blog"
weight = -120
identifier = "blog"
url = "/"

[[menu.main]]
name = "About"
weight = -110
identifier = "about"
url = "/about/me"

[[menu.main]]
name = "Photography"
weight = -110
identifier = "photography"
url = "/photography"
