baseURL = "/"
title = "Larry Wright"
languageCode = "en-us"
paginate = "10" # Number of posts per page
theme = "larrywright.me"
pygmentsCodeFences = true
# disqusShortname = "curiousityproject" # Enable comments by entering your Disqus shortname
# googleAnalytics = "UA-100582-3" # Enable Google Analytics by entering your tracking id

[Author]
    name = "Larry Wright"
    
[params]
    subtitle = "The Journal of a Curious Person" # Subtitle of your site
    defaultDescription = "Larry Wright's personal blog. A little bit of everything, mostly nerdy."
    facebook = "https://www.facebook.com/larrywright"
    twitter = "https://twitter.com/larrywright"
    linkedin = "https://www.linkedin.com/in/larrywright/"
    github = "https://github.com/larrywright"
    email = "larrywright@gmail.com"
    home = "Home"
    truncate = true

 [taxonomies]
    # Optional. Use if you want tags and lists.
    category = "categories"

[params.widgets]
    search = true 
    recent_articles = true 
    categories = true # Enable "Categories" widget
    tags = true # Enable "Tags" widget
        tags_counter = false # Enable counter for each tag in "Tags" widget (disabled by default)


[[menu.main]]
name = "About"
weight = 1
identifier = "about"
url = "/about/me"

[[menu.main]]
name = "Blog"
weight = 2
identifier = "posts"
url = "/post/"

[[menu.main]]
name = "Photos"
weight = 2
identifier = "photo"
url = "/photo/"

[[menu.main]]
name = "Now"
weight = 4
identifier = "now"
url = "/now"
