baseURL = "http://larrywright.me/"
title = "Larry Wright"
languageCode = "en-us"
paginate = "10" # Number of posts per page
theme = "larrywright.me"
pygmentsCodeFences = true
googleAnalytics = "UA-100582-3"

[Author]
    name = "Larry Wright"
    
[params]
    subtitle = "The Journal of a Curious Person" # Subtitle of your site
    defaultDescription = "Words and pictures by Larry Wright. A little bit of everything, mostly nerdy."
    facebook = "larrywright"
    twitter = "larrywright"
    linkedin = "https://www.linkedin.com/in/larrywright/"
    github = "https://github.com/larrywright"
    email = "larrywright@gmail.com"
    home = "Home"
    truncate = true
    avatar = "larry.jpg"
#    mainSections = ["post", "photo"]
    mainSections = ["post"]

 [taxonomies]
    # Optional. Use if you want tags and lists.
    category = "categories"

[params.widgets]
    search = true 
    recent_articles = true 
    categories = true # Enable "Categories" widget
    tags = true # Enable "Tags" widget
        tags_counter = false # Enable counter for each tag in "Tags" widget (disabled by default)


[[menu.main]]
name = "About"
weight = 1
identifier = "about"
url = "/about/me"

[[menu.main]]
name = "Blog"
weight = 2
identifier = "posts"
url = "/post/"

[[menu.main]]
name = "Photos"
weight = 2
identifier = "photo"
url = "/photo/"

[[menu.main]]
name = "Now"
weight = 4
identifier = "now"
url = "/now"
