version: '2'
services:
  site:
    build: .
    ports:
      - "1313:1313"
    volumes:
      - /usr/share/nginx/html
    environment:
      HUGO_BASE_URL: "http://localhost"
  web:
    image: "nginx"
    ports:
      - "80:80"
    volumes_from:
      - site:ro
    
