baseURL = "/"
title = "Larry Wright"
languageCode = "en-us"
paginate = "10" # Number of posts per page
theme = "hyde-x-larry"
# disqusShortname = "curiousityproject" # Enable comments by entering your Disqus shortname
# googleAnalytics = "UA-100582-3" # Enable Google Analytics by entering your tracking id

[Author]
    name = "Larry Wright"
    avatar = "images/headshot-256x256.png"

[params]
    tagline = "The Journal of a Curious Person" # Subtitle of your site
    defaultDescription = "Larry Wright's personal blog. A little bit of everything, mostly nerdy."
    facebook = "larrywright"
    twitter = "larrywright"
    linkedin = "larrywright"
    github = "larrywright"
    email = "larrywright@gmail.com"
    avatar = "images/headshot-256x256.png"
    gravatarHash = "340fc2e514619a65816216c7a9fe6b1b"
    sidebar = "left"
    brand = "The Journal of a Curious Person"
    topline = "Larry Wright's personal blog. A little bit of everything, mostly nerdy."
    home = "Home"
    truncate = true
    highlight = "tomorrow-night"

 [taxonomies]
    # Optional. Use if you want tags and lists.
    category = "categories"

[params.widgets]
    search = true 
    recent_articles = true 
    categories = true # Enable "Categories" widget
    tags = true # Enable "Tags" widget
        tags_counter = false # Enable counter for each tag in "Tags" widget (disabled by default)


[[menu.main]]
name = "About"
weight = 2
identifier = "about"
url = "/about/me"

[[menu.main]]
name = "Blog"
weight = 1
identifier = "posts"
url = "/post/"

[[menu.main]]
name = "Photography"
weight = 3
identifier = "photography"
url = "https://larrywright.myportfolio.com"

[[menu.main]]
name = "Now"
weight = 4
identifier = "now"
url = "/now"
